spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_service
    username: postgres
    password: Phieu2106
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: contract-service
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084


CUSTOMER_URL: http://localhost:8082
INSURANCE_URL: http://localhost:8083


